# Random Fun Python Functions

This notebook contains functions that create staircases, sums hourglass figures in arrays, etc. As always, more to come!

## hourglassSums(array)

Created on Fri Dec 27 19:43:05 2019;
hourglassSum takes a square array and calculates the sums of all of the 
hourglass shapes composed of 3x3 arrays within the original array and stores
them in a list. Then the list is sorted and the largest of the sums is returned.
@author: Erik Larsen

In [27]:
n=10

In [28]:
arr=np.round(np.random.randn(n,n)*3-np.eye(n)*2,2)     

In [29]:
import numpy as np

def hourglassSum(array):
    shapes=np.shape(array)
    error='error: My apologies, the input must be a square array with n>2.'
    if shapes[0]!=shapes[1]:
        return(print(error))
    if shapes[0]<=2 or shapes[1]<=2:
        return(print(error))
    sums_list=[]
    for i in range(0,len(array)-2):
        for j in range(0,len(array)-2):
            test_arr=np.array([np.eye(3)])*0
            test_arr=arr[i:i+3,j:j+3]
            temp1=test_arr[1,0]
            temp2=test_arr[1,2]
            test_arr[1,0]=0
            test_arr[1,2]=0
            sums=sum(sum(test_arr))
            sums_list.append(sums)
            test_arr[1,0]=temp1
            test_arr[1,2]=temp2
    sums_list=np.sort(sums_list)
    optimus=sums_list[-1]
    print('\n','optimus=')
    return(optimus)

In [30]:
if n<= 10:
    print(arr)

[[ 0.11  5.78 -3.1  -3.82  0.08  1.01 -1.55  2.8   1.18 -4.81]
 [ 0.13  2.13  0.96 -4.01 -1.74  2.62 -1.3   0.98  0.56  2.08]
 [-2.31 -2.8  -6.1  -2.42  0.99 -0.33  2.74  0.6  -3.62 -0.47]
 [-2.3   0.89 -6.45 -1.41 -3.64 -0.02 -2.16 -1.19  5.64  1.47]
 [-0.69  0.28  3.94 -0.81 -4.49 -1.82  0.01  6.67 -0.44 -1.69]
 [ 2.1  -3.03  3.84  1.15  0.68 -1.2   0.74  6.81 -2.85 -1.06]
 [-1.79  0.97 -1.18 -0.98  1.86 -1.45  4.25 -5.74  1.22 -1.4 ]
 [-1.06  0.73 -1.28 -3.96 -0.38  1.28 -5.78 -2.77  2.48 -0.12]
 [-3.2   3.02  1.64  5.21 -0.91 -0.39 -3.33  4.24 -4.68 -2.08]
 [ 4.73  5.12 -5.71 -3.49  2.13 -2.37  3.4  -0.92  2.58 -1.25]]


In [31]:
hourglassSum(arr)


 optimus=


13.659999999999998

## stairCreator(n)

Created on Dec 14 09:47:53 2019;
This function takes an input, n, and prints a right aligned staircase made 
of # signs.
@author: Erik Larsen

In [32]:
n=8

In [33]:
def stairCreator(n):
    #create a list housing the stairs:
    staircase=[]
    #populate the list:
    for i in range(0,n):
        row=' '*((n-1)-i)+'#'*(i+1)
        staircase.append(row)
    #print the staircase one row at a time:
    for i in staircase:
        print(i)

In [34]:
stairCreator(n)

       #
      ##
     ###
    ####
   #####
  ######
 #######
########
